---
title: "Fitbit R Markdown"
author: "Suvek"
date: "02/06/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Background
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset).

```

> setwd("D:/Data Science/Fitbit Data Set")
> getwd()  ## Initialising the directory ##
[1] "D:/Data Science/Fitbit Data Set"
> training<-read.csv("pml-training.csv", header = T, sep = ",") ## Loading the training data set into R ##
> dim(training)
[1] 19622   160
> 
> library(caret)
Loading required package: lattice
Loading required package: ggplot2
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
> NZV<-nearZeroVar(training)   ## Identifying the columns which have no variation in data ##
> trainset<-training[,-NZV]    ## And removing the same from the training dataset ##
> dim(trainset)
[1] 19622   100
> 
> AllNA<-sapply(trainset, function(x){mean(is.na(x))>0.95}) ## Removing all NA's from the dataset ##
> trainset<-trainset[,AllNA == F]  
> dim(trainset)
[1] 19622    59
> 
> trainset<-trainset[,-(1:5)]   ## Removing the first 5 coumns from the training set since they are person specific columns ##
> dim(trainset)
[1] 19622    54
>  
> inTrain<-createDataPartition(trainset$classe,p=0.7, list = F)    ## Dividing the train set into training set and testing set ##
> trainingset<-trainset[inTrain,]
> testingset<-trainset[-inTrain,]
> dim(trainingset)
[1] 13737    54
> 
> library(corrplot)                                 ## Plotting the co-relation matrix to identify the most effective predictors ##
corrplot 0.84 loaded
> corMatrix<-cor(trainingset[,-54])  
> corrplot(corMatrix, order = "FPC", method = "color", type = "lower", tl.cex = 0.5)
> 
> 
> set.seed(12345)                          ## Training & Prediction using Random Forest ##
> controlRF<-trainControl(method = "cv", number = 3, verboseIter = F)               ## Very important to build this function to reduce the number of iterations ##
> modFitRandForest<-train(classe~.,data = trainingset, method = "rf", trControl = controlRF)              ## If controlRF not used, then training dataset takes very long time ##
> modFitRandForest$finalModel

Call:
 randomForest(x = x, y = y, mtry = param$mtry) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 27

        OOB estimate of  error rate: 0.22%
Confusion matrix:
     A    B    C    D    E  class.error
A 3904    1    0    0    1 0.0005120328
B    5 2651    1    1    0 0.0026335591
C    0    5 2389    2    0 0.0029215359
D    0    0    9 2243    0 0.0039964476
E    0    0    0    5 2520 0.0019801980
> 
> 
> predictRandForest<-predict(modFitForest, newdata = testingset)
Error in predict(modFitForest, newdata = testingset) : 
  object 'modFitForest' not found
> confRandForest<-confusionMatrix(predictRandForest, testingset$classe)
Error in confusionMatrix(predictRandForest, testingset$classe) : 
  object 'predictRandForest' not found
> confRandForest
Error: object 'confRandForest' not found
> 
> 
> set.seed(12345) ## Training & Prediction using Decision Trees ##
> library(rpart) 
> modFitDecTree<-rpart(classe~.,data = trainingset, method = "class")
> library(rattle)
Rattle: A free graphical interface for data science with R.
Version 5.2.0 Copyright (c) 2006-2018 Togaware Pty Ltd.
Type 'rattle()' to shake, rattle, and roll your data.
> fancyRpartPlot(modFitDecTree)  ## Gives visual representation of division of variables into Decision Trees ##
Warning message:
labs do not fit even at cex 0.15, there may be some overplotting 
> 
> 
> predictDecTree<-predict(modFitDecTree, newdata = testingset, type = "class")
> confMatDecTree<-confusionMatrix(predictDecTree, testingset$classe)
> confMatDecTree
Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 1436   83    4   12   11
         B  145  879   67   74   47
         C    1   56  822   32    5
         D   77   50  120  787   68
         E   15   71   13   59  951

Overall Statistics
                                          
               Accuracy : 0.8284          
                 95% CI : (0.8185, 0.8379)
    No Information Rate : 0.2845          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.7836          
                                          
 Mcnemar's Test P-Value : < 2.2e-16       

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            0.8578   0.7717   0.8012   0.8164   0.8789
Specificity            0.9739   0.9298   0.9807   0.9360   0.9671
Pos Pred Value         0.9288   0.7252   0.8974   0.7142   0.8575
Neg Pred Value         0.9451   0.9444   0.9589   0.9630   0.9726
Prevalence             0.2845   0.1935   0.1743   0.1638   0.1839
Detection Rate         0.2440   0.1494   0.1397   0.1337   0.1616
Detection Prevalence   0.2627   0.2059   0.1556   0.1873   0.1884
Balanced Accuracy      0.9159   0.8508   0.8909   0.8762   0.9230
> 
> 
> set.seed(12345)   ## Generalised Boosting Method ##
> controlGBM<-trainControl(method = "repeatedCV", number = 5, repeats = 1)
Warning message:
`repeats` has no meaning for this resampling method. 
> modFitGBM<-train(classe~.,data =trainingset, method ="gbm", trControl = controlGBM)
Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1234
     2        1.5238             nan     0.1000    0.0898
     3        1.4650             nan     0.1000    0.0681
     4        1.4208             nan     0.1000    0.0531
     5        1.3846             nan     0.1000    0.0511
     6        1.3514             nan     0.1000    0.0435
     7        1.3234             nan     0.1000    0.0402
     8        1.2980             nan     0.1000    0.0343
     9        1.2764             nan     0.1000    0.0369
    10        1.2507             nan     0.1000    0.0300
    20        1.0906             nan     0.1000    0.0201
    40        0.9051             nan     0.1000    0.0082
    60        0.7935             nan     0.1000    0.0060
    80        0.7119             nan     0.1000    0.0044
   100        0.6489             nan     0.1000    0.0040
   120        0.5964             nan     0.1000    0.0034
   140        0.5500             nan     0.1000    0.0024
   150        0.5291             nan     0.1000    0.0021

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1881
     2        1.4857             nan     0.1000    0.1272
     3        1.4034             nan     0.1000    0.1086
     4        1.3329             nan     0.1000    0.0860
     5        1.2766             nan     0.1000    0.0813
     6        1.2250             nan     0.1000    0.0636
     7        1.1838             nan     0.1000    0.0601
     8        1.1456             nan     0.1000    0.0666
     9        1.1056             nan     0.1000    0.0511
    10        1.0741             nan     0.1000    0.0414
    20        0.8499             nan     0.1000    0.0236
    40        0.6220             nan     0.1000    0.0140
    60        0.4847             nan     0.1000    0.0045
    80        0.3899             nan     0.1000    0.0048
   100        0.3262             nan     0.1000    0.0027
   120        0.2737             nan     0.1000    0.0043
   140        0.2334             nan     0.1000    0.0025
   150        0.2146             nan     0.1000    0.0046

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.2249
     2        1.4635             nan     0.1000    0.1651
     3        1.3593             nan     0.1000    0.1317
     4        1.2742             nan     0.1000    0.1109
     5        1.2046             nan     0.1000    0.0902
     6        1.1483             nan     0.1000    0.0876
     7        1.0920             nan     0.1000    0.0681
     8        1.0482             nan     0.1000    0.0684
     9        1.0049             nan     0.1000    0.0586
    10        0.9681             nan     0.1000    0.0575
    20        0.7071             nan     0.1000    0.0272
    40        0.4591             nan     0.1000    0.0126
    60        0.3287             nan     0.1000    0.0047
    80        0.2545             nan     0.1000    0.0036
   100        0.1971             nan     0.1000    0.0039
   120        0.1559             nan     0.1000    0.0022
   140        0.1245             nan     0.1000    0.0007
   150        0.1127             nan     0.1000    0.0011

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1264
     2        1.5237             nan     0.1000    0.0851
     3        1.4670             nan     0.1000    0.0647
     4        1.4232             nan     0.1000    0.0554
     5        1.3862             nan     0.1000    0.0515
     6        1.3533             nan     0.1000    0.0446
     7        1.3235             nan     0.1000    0.0425
     8        1.2966             nan     0.1000    0.0340
     9        1.2749             nan     0.1000    0.0364
    10        1.2511             nan     0.1000    0.0302
    20        1.0867             nan     0.1000    0.0191
    40        0.9048             nan     0.1000    0.0075
    60        0.7944             nan     0.1000    0.0066
    80        0.7123             nan     0.1000    0.0047
   100        0.6470             nan     0.1000    0.0043
   120        0.5952             nan     0.1000    0.0034
   140        0.5479             nan     0.1000    0.0023
   150        0.5267             nan     0.1000    0.0029

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1848
     2        1.4877             nan     0.1000    0.1313
     3        1.4025             nan     0.1000    0.1120
     4        1.3307             nan     0.1000    0.0832
     5        1.2759             nan     0.1000    0.0789
     6        1.2272             nan     0.1000    0.0731
     7        1.1796             nan     0.1000    0.0602
     8        1.1419             nan     0.1000    0.0597
     9        1.1045             nan     0.1000    0.0438
    10        1.0764             nan     0.1000    0.0529
    20        0.8436             nan     0.1000    0.0216
    40        0.6154             nan     0.1000    0.0133
    60        0.4823             nan     0.1000    0.0073
    80        0.3900             nan     0.1000    0.0082
   100        0.3195             nan     0.1000    0.0038
   120        0.2671             nan     0.1000    0.0037
   140        0.2274             nan     0.1000    0.0017
   150        0.2092             nan     0.1000    0.0031

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.2442
     2        1.4539             nan     0.1000    0.1628
     3        1.3511             nan     0.1000    0.1282
     4        1.2685             nan     0.1000    0.1141
     5        1.1958             nan     0.1000    0.0853
     6        1.1412             nan     0.1000    0.0714
     7        1.0954             nan     0.1000    0.0693
     8        1.0505             nan     0.1000    0.0750
     9        1.0040             nan     0.1000    0.0669
    10        0.9629             nan     0.1000    0.0577
    20        0.7027             nan     0.1000    0.0240
    40        0.4585             nan     0.1000    0.0198
    60        0.3297             nan     0.1000    0.0093
    80        0.2473             nan     0.1000    0.0051
   100        0.1931             nan     0.1000    0.0072
   120        0.1534             nan     0.1000    0.0021
   140        0.1240             nan     0.1000    0.0022
   150        0.1111             nan     0.1000    0.0031

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1259
     2        1.5248             nan     0.1000    0.0879
     3        1.4683             nan     0.1000    0.0671
     4        1.4244             nan     0.1000    0.0542
     5        1.3889             nan     0.1000    0.0490
     6        1.3560             nan     0.1000    0.0461
     7        1.3271             nan     0.1000    0.0396
     8        1.3021             nan     0.1000    0.0403
     9        1.2751             nan     0.1000    0.0325
    10        1.2542             nan     0.1000    0.0287
    20        1.0910             nan     0.1000    0.0213
    40        0.9054             nan     0.1000    0.0095
    60        0.7937             nan     0.1000    0.0070
    80        0.7108             nan     0.1000    0.0048
   100        0.6456             nan     0.1000    0.0040
   120        0.5913             nan     0.1000    0.0027
   140        0.5448             nan     0.1000    0.0027
   150        0.5243             nan     0.1000    0.0013

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1845
     2        1.4903             nan     0.1000    0.1310
     3        1.4047             nan     0.1000    0.1121
     4        1.3329             nan     0.1000    0.0875
     5        1.2774             nan     0.1000    0.0792
     6        1.2260             nan     0.1000    0.0710
     7        1.1809             nan     0.1000    0.0646
     8        1.1411             nan     0.1000    0.0492
     9        1.1100             nan     0.1000    0.0556
    10        1.0763             nan     0.1000    0.0460
    20        0.8445             nan     0.1000    0.0252
    40        0.6241             nan     0.1000    0.0118
    60        0.4793             nan     0.1000    0.0043
    80        0.3860             nan     0.1000    0.0061
   100        0.3219             nan     0.1000    0.0018
   120        0.2679             nan     0.1000    0.0057
   140        0.2249             nan     0.1000    0.0037
   150        0.2053             nan     0.1000    0.0024

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.2432
     2        1.4576             nan     0.1000    0.1735
     3        1.3490             nan     0.1000    0.1381
     4        1.2642             nan     0.1000    0.0949
     5        1.2037             nan     0.1000    0.0922
     6        1.1452             nan     0.1000    0.0836
     7        1.0930             nan     0.1000    0.0835
     8        1.0400             nan     0.1000    0.0550
     9        1.0046             nan     0.1000    0.0632
    10        0.9653             nan     0.1000    0.0534
    20        0.6997             nan     0.1000    0.0255
    40        0.4535             nan     0.1000    0.0124
    60        0.3245             nan     0.1000    0.0071
    80        0.2458             nan     0.1000    0.0060
   100        0.1915             nan     0.1000    0.0037
   120        0.1522             nan     0.1000    0.0030
   140        0.1236             nan     0.1000    0.0027
   150        0.1109             nan     0.1000    0.0018

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1234
     2        1.5251             nan     0.1000    0.0839
     3        1.4675             nan     0.1000    0.0650
     4        1.4243             nan     0.1000    0.0537
     5        1.3890             nan     0.1000    0.0499
     6        1.3554             nan     0.1000    0.0398
     7        1.3287             nan     0.1000    0.0440
     8        1.3023             nan     0.1000    0.0402
     9        1.2752             nan     0.1000    0.0332
    10        1.2537             nan     0.1000    0.0293
    20        1.0892             nan     0.1000    0.0188
    40        0.9064             nan     0.1000    0.0090
    60        0.7966             nan     0.1000    0.0058
    80        0.7119             nan     0.1000    0.0049
   100        0.6479             nan     0.1000    0.0041
   120        0.5929             nan     0.1000    0.0033
   140        0.5475             nan     0.1000    0.0014
   150        0.5285             nan     0.1000    0.0027

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1903
     2        1.4865             nan     0.1000    0.1262
     3        1.4035             nan     0.1000    0.1149
     4        1.3314             nan     0.1000    0.0855
     5        1.2757             nan     0.1000    0.0814
     6        1.2232             nan     0.1000    0.0678
     7        1.1802             nan     0.1000    0.0675
     8        1.1395             nan     0.1000    0.0530
     9        1.1066             nan     0.1000    0.0482
    10        1.0769             nan     0.1000    0.0395
    20        0.8534             nan     0.1000    0.0305
    40        0.6225             nan     0.1000    0.0119
    60        0.4904             nan     0.1000    0.0104
    80        0.4013             nan     0.1000    0.0055
   100        0.3331             nan     0.1000    0.0033
   120        0.2798             nan     0.1000    0.0027
   140        0.2369             nan     0.1000    0.0028
   150        0.2197             nan     0.1000    0.0025

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.2402
     2        1.4574             nan     0.1000    0.1695
     3        1.3517             nan     0.1000    0.1297
     4        1.2690             nan     0.1000    0.1203
     5        1.1967             nan     0.1000    0.0897
     6        1.1390             nan     0.1000    0.0773
     7        1.0886             nan     0.1000    0.0682
     8        1.0450             nan     0.1000    0.0761
     9        0.9985             nan     0.1000    0.0657
    10        0.9577             nan     0.1000    0.0635
    20        0.7010             nan     0.1000    0.0224
    40        0.4496             nan     0.1000    0.0151
    60        0.3255             nan     0.1000    0.0060
    80        0.2558             nan     0.1000    0.0044
   100        0.1971             nan     0.1000    0.0017
   120        0.1574             nan     0.1000    0.0033
   140        0.1291             nan     0.1000    0.0019
   150        0.1153             nan     0.1000    0.0011

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1249
     2        1.5254             nan     0.1000    0.0859
     3        1.4680             nan     0.1000    0.0615
     4        1.4258             nan     0.1000    0.0568
     5        1.3893             nan     0.1000    0.0519
     6        1.3566             nan     0.1000    0.0399
     7        1.3287             nan     0.1000    0.0359
     8        1.3061             nan     0.1000    0.0413
     9        1.2782             nan     0.1000    0.0340
    10        1.2568             nan     0.1000    0.0345
    20        1.0912             nan     0.1000    0.0162
    40        0.9103             nan     0.1000    0.0097
    60        0.7955             nan     0.1000    0.0072
    80        0.7131             nan     0.1000    0.0046
   100        0.6452             nan     0.1000    0.0038
   120        0.5935             nan     0.1000    0.0034
   140        0.5453             nan     0.1000    0.0023
   150        0.5237             nan     0.1000    0.0031

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.1802
     2        1.4898             nan     0.1000    0.1270
     3        1.4062             nan     0.1000    0.1097
     4        1.3358             nan     0.1000    0.0922
     5        1.2774             nan     0.1000    0.0746
     6        1.2290             nan     0.1000    0.0676
     7        1.1852             nan     0.1000    0.0611
     8        1.1470             nan     0.1000    0.0595
     9        1.1097             nan     0.1000    0.0496
    10        1.0772             nan     0.1000    0.0468
    20        0.8517             nan     0.1000    0.0341
    40        0.6164             nan     0.1000    0.0096
    60        0.4855             nan     0.1000    0.0095
    80        0.3946             nan     0.1000    0.0033
   100        0.3254             nan     0.1000    0.0031
   120        0.2792             nan     0.1000    0.0027
   140        0.2367             nan     0.1000    0.0024
   150        0.2179             nan     0.1000    0.0014

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.2423
     2        1.4583             nan     0.1000    0.1712
     3        1.3538             nan     0.1000    0.1386
     4        1.2657             nan     0.1000    0.1025
     5        1.2000             nan     0.1000    0.0959
     6        1.1385             nan     0.1000    0.0794
     7        1.0880             nan     0.1000    0.0698
     8        1.0428             nan     0.1000    0.0717
     9        0.9974             nan     0.1000    0.0602
    10        0.9604             nan     0.1000    0.0509
    20        0.6924             nan     0.1000    0.0257
    40        0.4489             nan     0.1000    0.0133
    60        0.3289             nan     0.1000    0.0051
    80        0.2504             nan     0.1000    0.0061
   100        0.1964             nan     0.1000    0.0037
   120        0.1567             nan     0.1000    0.0018
   140        0.1240             nan     0.1000    0.0037
   150        0.1112             nan     0.1000    0.0017

Iter   TrainDeviance   ValidDeviance   StepSize   Improve
     1        1.6094             nan     0.1000    0.2401
     2        1.4575             nan     0.1000    0.1708
     3        1.3527             nan     0.1000    0.1342
     4        1.2689             nan     0.1000    0.1144
     5        1.1983             nan     0.1000    0.0956
     6        1.1381             nan     0.1000    0.0846
     7        1.0841             nan     0.1000    0.0665
     8        1.0413             nan     0.1000    0.0854
     9        0.9902             nan     0.1000    0.0498
    10        0.9588             nan     0.1000    0.0536
    20        0.6903             nan     0.1000    0.0272
    40        0.4556             nan     0.1000    0.0141
    60        0.3381             nan     0.1000    0.0102
    80        0.2527             nan     0.1000    0.0070
   100        0.1945             nan     0.1000    0.0051
   120        0.1545             nan     0.1000    0.0015
   140        0.1258             nan     0.1000    0.0023
   150        0.1140             nan     0.1000    0.0015

> modFitGBM$finalModel
A gradient boosted model with multinomial loss function.
150 iterations were performed.
There were 53 predictors of which 53 had non-zero influence.
> 
> 
> predictGBM<-predict(modFitGBM,newdata = testingset)
> confMatGBM<-confusionMatrix(predictGBM, testingset$classe)
> confMatGBM
Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 1672    7    0    1    0
         B    0 1127    6    4    3
         C    0    5 1015    7    0
         D    1    0    4  948   17
         E    1    0    1    4 1062

Overall Statistics
                                          
               Accuracy : 0.9896          
                 95% CI : (0.9867, 0.9921)
    No Information Rate : 0.2845          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.9869          
                                          
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            0.9988   0.9895   0.9893   0.9834   0.9815
Specificity            0.9981   0.9973   0.9975   0.9955   0.9988
Pos Pred Value         0.9952   0.9886   0.9883   0.9773   0.9944
Neg Pred Value         0.9995   0.9975   0.9977   0.9967   0.9958
Prevalence             0.2845   0.1935   0.1743   0.1638   0.1839
Detection Rate         0.2841   0.1915   0.1725   0.1611   0.1805
Detection Prevalence   0.2855   0.1937   0.1745   0.1648   0.1815
Balanced Accuracy      0.9985   0.9934   0.9934   0.9895   0.9901
> 
> 
> ## The Random Forest Model has the highest accuracy. Hence we select the same for our prediction purpose ##
> 
> testing<-read.csv("pml-testing.csv", header = T, sep = ",")
> predictTEST<-predict(modFitRandForest, newdata = testing)
> predictTEST
 [1] B A B A A E D B A A B C B A E E A B B B
Levels: A B C D E
> 
> testing$predict<-predictTEST
```


